"""screening_run / screening_result 表定义（SQLAlchemy Table，供仓储使用；索引见 Alembic 迁移）。"""

from __future__ import annotations

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    Column,
    Date,
    DateTime,
    ForeignKey,
    MetaData,
    Numeric,
    String,
    Table,
    Text,
    UniqueConstraint,
)

metadata = MetaData()

screening_run = Table(
    "screening_run",
    metadata,
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("external_uuid", String(36), nullable=False, unique=True),
    Column("status", String(32), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("finished_at", DateTime(timezone=True), nullable=True),
    Column("universe_size", BigInteger, nullable=True),
    Column("snapshot_ok", BigInteger, nullable=True),
    Column("snapshot_failed", BigInteger, nullable=True),
    Column("provider_label", String(128), nullable=True),
    Column("meta_json", JSON, nullable=True),
)

screening_result = Table(
    "screening_result",
    metadata,
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column(
        "run_id",
        BigInteger,
        ForeignKey("screening_run.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("symbol", String(32), nullable=False),
    Column("graham_score", Numeric(12, 4), nullable=False),
    Column("buffett_score", Numeric(12, 4), nullable=False),
    Column("graham_json", JSON, nullable=False),
    Column("buffett_json", JSON, nullable=False),
    Column("provenance_json", JSON, nullable=True),
    Column("combined_score", Numeric(12, 4), nullable=True),
    Column("coverage_ok", Boolean, nullable=False),
    Column("third_lens_score", Numeric(12, 4), nullable=True),
    Column("third_lens_json", JSON, nullable=True),
    Column("final_triple_score", Numeric(12, 4), nullable=True),
    Column("run_fact_json", JSON, nullable=True),
    Column("market_cap", Numeric(24, 4), nullable=True),
    Column("pe_ttm", Numeric(24, 8), nullable=True),
    Column("investment_quality_json", JSON, nullable=True),
    Column("iq_decision", String(32), nullable=True),
    UniqueConstraint("run_id", "symbol", name="uk_screening_result_run_symbol"),
)

financial_snapshot = Table(
    "financial_snapshot",
    metadata,
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("symbol", String(32), nullable=False),
    Column("financials_end_date", String(16), nullable=False, server_default=""),
    Column("snapshot_json", JSON, nullable=False),
    Column("data_source", String(64), nullable=True),
    Column("fetched_at", DateTime(timezone=True), nullable=False),
    Column("content_hash", String(64), nullable=True),
    UniqueConstraint("symbol", "financials_end_date", name="uk_financial_snapshot_sym_period"),
)

company_ai_analysis = Table(
    "company_ai_analysis",
    metadata,
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("ts_code", String(32), nullable=False),
    Column("analysis_date", Date, nullable=False),
    Column("run_id", BigInteger, ForeignKey("screening_run.id", ondelete="SET NULL"), nullable=True),
    Column("ai_score", Numeric(8, 4), nullable=False),
    Column("ai_score_rationale", String(512), nullable=True),
    Column("summary", Text, nullable=False),
    Column("key_metrics_commentary", Text, nullable=False),
    Column("risks", Text, nullable=False),
    Column("alignment_with_scores", Text, nullable=False),
    Column("narrative_markdown", Text, nullable=False),
    Column("context_hash", String(64), nullable=False),
    Column("prompt_version", String(32), nullable=False),
    Column("model", String(128), nullable=False),
    Column("generated_at", DateTime(timezone=True), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("dcf_json", JSON, nullable=True),
    Column("dcf_ok", Boolean, nullable=True),
    Column("dcf_headline", String(512), nullable=True),
    Column("opportunity_score", Numeric(8, 4), nullable=True),
    Column("opportunity_score_rationale", String(512), nullable=True),
    UniqueConstraint("ts_code", "analysis_date", name="uk_company_ai_analysis_ts_date"),
)

ingestion_job = Table(
    "ingestion_job",
    metadata,
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("job_type", String(64), nullable=False),
    Column("scheduled_date", Date, nullable=False),
    Column("params_hash", String(32), nullable=False),
    Column("status", String(32), nullable=False),
    Column("cursor_ts_code", String(16), nullable=True),
    Column("universe_fingerprint", String(64), nullable=True),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("job_type", "scheduled_date", "params_hash", name="uk_ingestion_job_key"),
)

security_reference = Table(
    "security_reference",
    metadata,
    Column("ts_code", String(16), primary_key=True, nullable=False),
    Column("symbol", String(16), nullable=True),
    Column("name", String(64), nullable=True),
    Column("area", String(32), nullable=True),
    Column("industry", String(64), nullable=True),
    Column("fullname", String(256), nullable=True),
    Column("enname", String(256), nullable=True),
    Column("cnspell", String(32), nullable=True),
    Column("market", String(32), nullable=True),
    Column("exchange", String(16), nullable=True),
    Column("curr_type", String(16), nullable=True),
    Column("list_status", String(8), nullable=True),
    Column("list_date", String(16), nullable=True),
    Column("delist_date", String(16), nullable=True),
    Column("is_hs", String(8), nullable=True),
    Column("synced_at", DateTime(timezone=True), nullable=False),
)
